---
- name: Create instance ports
  block:
    - name: Create network ports
      os_migrate.vmware_migration_kit.create_network_port:
        cloud: dst
        os_migrate_nics_file_path: "{{ os_migrate_data_dir }}/nics_{{ vm_name }}.json"
        vm_name: "{{ vm_name }}"
        used_mapped_networks: true
        security_groups: ["{{ security_groups | default('default') }}"]
      register: ports_uuid
      when: used_mapped_networks|default(true)|bool

    - name: Create network port
      os_migrate.vmware_migration_kit.create_network_port:
        cloud: dst
        os_migrate_nics_file_path: "{{ os_migrate_data_dir }}/macs_{{ vm_name }}.json"
        vm_name: "{{ vm_name }}"
        used_mapped_networks: false
        security_groups: ["{{ security_groups | default('default') }}"]
        network_name: "{{ openstack_private_network}}"
      register: ports_uuid
      when: not used_mapped_networks|default(true)|bool

    - name: Extract port info
      set_fact:
        nics: " {{ ports | default([]) }}"
  when: os_migrate_create_network_port|default(true)|bool

- name: Set nics fact for os instance creation
  set_fact:
    nics: "net-name={{ openstack_private_network }}"
  when:
    - not os_migrate_create_network_port|default(true)|bool
    - openstack_private_network is defined