---
- name: Get vCenter network config for {{ vm_name }}
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    validate_certs: false
    name: "{{ vm_name }}"
    gather_network_info: true
  register: network_info

- name: Dump network_info to json file
  copy:
    content: "{{ network_info }}"
    dest: "{{ os_migrate_data_dir }}/network_info_{{ vm_name }}.json"
  delegate_to: localhost
  run_once: true

- name: Extract nic info based on network_map
  set_fact:
    guest_nic: "{{ guest_nic | default([]) + [ {'vlan': mapped_vlan, 'mac': item.mac_addr}] }}"
  loop: "{{ network_info.network_info }}"
  vars:
    mapped_vlan: "{{ network_map.get(item.network_name, 'UNMAPPED') }}"
  when:
    - mapped_vlan != 'UNMAPPED'
    - used_mapped_networks|default(true)|bool

- name: Dump guest_nic to json file
  copy:
    content: "{{ guest_nic }}"
    dest: "{{ os_migrate_data_dir }}/nics_{{ vm_name }}.json"
  delegate_to: localhost
  run_once: true
  when: used_mapped_networks|default(true)|bool

- name: Extract mac address
  set_fact:
    guest_mac: "{{ guest_mac | default([]) + [item.mac_addr] }}"
  loop: "{{ network_info.network_info }}"
  when: used_mapped_networks|default(false)|bool

- name: Dump guest_mac to json file
  copy:
    content: "{{ guest_mac }}"
    dest: "{{ os_migrate_data_dir }}/macs_{{ vm_name }}.json"
  delegate_to: localhost
  run_once: true
  when: used_mapped_networks|default(false)|bool