---
- name: Gather one specific VM
  community.vmware.vmware_vm_info:
    validate_certs: false
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vm_name: "{{ vm_name }}"
  register: vm_info

- name: Dump vm_info file
  copy:
    content: "{{ vm_info }}"
    dest: "{{ os_migrate_data_dir }}/vm_info_{{ vm_name }}.json"
  delegate_to: localhost
  run_once: true
