- name: Make sure required package are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
    - libvirt
    - virt-v2v
    - qemu-kvm
    - python3-openstackclient

- name: Set Openstack credentials clouds.yaml file
  ansible.builtin.copy:
    src: "{{ os_migrate_clouds_path|default(os_migrate_data_dir ~ '/clouds.yaml') }}"
    dest: "~/.config/openstack/clouds.yaml"

    